sonar.projectKey=nick-llewellyn_nts
sonar.organization=nick-llewellyn

# Paths to sources and tests
sonar.sources=lib
sonar.tests=test

# Exclude generated code from analysis and coverage
sonar.exclusions=lib/src/ffi/**

# Location of coverage report
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code
sonar.sourceEncoding=UTF-8
