// Crate root for `nts_rust`.
//
// Module layout:
// - `api`            — surface exposed across the FFI boundary to Dart.
// - `nts`            — internal RFC 8915 protocol layer (KE, NTPv4, AEAD).
//                      Not yet on the FFI surface; wired up in phase 3.
// - `frb_generated`  — produced by `flutter_rust_bridge_codegen generate`.
//                      Do not edit by hand; regenerate after changing `api/`.

// Hand-written code in this crate is `unsafe`-free. The only `unsafe`
// blocks live inside `frb_generated.rs`, the FFI dispatch shim that
// `flutter_rust_bridge_codegen` emits — that module is exempted via a
// per-item `#[allow(unsafe_code)]` on its `mod` declaration below.
// `deny` (not `forbid`) is deliberate: `forbid` cannot be relaxed by a
// per-item `allow`, and the FRB-emitted shim genuinely needs `unsafe`
// to cross the C ABI. Any new `unsafe` block in our own modules will
// fail to compile and force a deliberate per-item override decision.
#![deny(unsafe_code)]

pub mod api;
// `frb_generated` is `flutter_rust_bridge_codegen` output and is
// regenerated wholesale by `dart run flutter_rust_bridge_codegen
// generate`; lint findings against it are not actionable from this
// repository. The allow-list mirrors the lint shapes the generator
// currently emits (wildcard imports of the `api::*` surface, terminal
// `wrap_normal::<...>(...)` calls without a trailing semicolon, the
// `else { return ...; }` shape on the trait-dispatch helpers, and the
// `unsafe` blocks on the C-ABI dispatch boundary).
#[allow(
    clippy::redundant_else,
    clippy::semicolon_if_nothing_returned,
    clippy::wildcard_imports,
    unsafe_code,
    reason = "generated by `flutter_rust_bridge_codegen`; do not edit by hand"
)]
mod frb_generated;
pub(crate) mod nts;

// Re-exports the protocol parsers for cargo-fuzz harnesses in
// `rust/fuzz/`, gated behind the `__internal-fuzz` Cargo feature so
// the surface stays out of the published API. The `nts` module
// remains `pub(crate)` for ordinary builds; flipping `__internal-fuzz`
// re-exposes only the specific parser entry points that fuzz targets
// need to drive, not the whole module tree. See
// `rust/Cargo.toml::[features]` for the policy on enabling this flag
// (fuzz / coverage crates only). The Cargo feature uses the
// canonical hyphenated form (`__internal-fuzz`); the module below
// substitutes underscore (`__internal_fuzz`) because Rust identifiers
// cannot contain hyphens (bd nts-b6m sub-item B).
#[cfg(feature = "__internal-fuzz")]
pub mod __internal_fuzz {
    pub use crate::nts::aead::AeadKey;
    pub use crate::nts::ke::KeError;
    pub use crate::nts::ntp::{
        parse_authenticator_body, parse_extensions, parse_server_response, NtpError,
    };
    pub use crate::nts::records::aead::AES_SIV_CMAC_256;
    pub use crate::nts::records::{parse_message, CodecError, Record};
    // Canned fixture constants shared with the unit tests. The
    // `parse_server_response` harness uses these as its fixed non-packet
    // arguments so the committed authenticated seeds (crafted with the
    // `test_helpers` builders) keep authenticating; re-exporting the
    // source-of-truth constants means a helper change either propagates
    // to the harness or fails to compile, instead of silently degrading
    // post-AEAD seed coverage (bd nts-jzh1 / NTS-67).
    pub use crate::nts::test_helpers::{CLIENT_TX, S2C, UID};

    /// Thin shim over `crate::nts::ke::validate_response` for the
    /// cargo-fuzz harness in `rust/fuzz/`. Discards the
    /// `KeOutcomePartial` payload (which stays private to the
    /// `nts::ke` module) and surfaces only `Result<(), KeError>`
    /// — the harness only asserts the call does not panic, the
    /// success-payload contents are uninteresting at the fuzz
    /// surface.
    pub fn validate_response(
        request_host: &str,
        offered_aead: &[u16],
        records: &[Record],
    ) -> Result<(), KeError> {
        crate::nts::ke::validate_response(request_host, offered_aead, records).map(|_| ())
    }
}

// Android-only: exports a JNI symbol that bootstraps `rustls-platform-verifier`
// against the Android system trust store. The matching Kotlin caller
// (`com.nllewellyn.nts.PlatformInit`) ships inside the `nts` Flutter
// plugin's Android library module (`<plugin>/android/`) and is invoked
// from `NtsPlugin.onAttachedToEngine` ahead of the Dart `main()`, before
// any FRB call can trigger a TLS handshake.
#[cfg(target_os = "android")]
pub mod android_init;

// iOS-only: installs a `tracing-oslog` subscriber so the crate's
// `tracing::*!` events and `log::*!` records (e.g. from `rustls`) reach
// Apple's unified logging system. Called once from `api::simple::init_app`
// in place of FRB's `setup_default_user_utils` on iOS — see the module
// docs for the rationale.
#[cfg(target_os = "ios")]
mod ios_init;
