// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nts.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class NtsRustLib
    extends BaseEntrypoint<NtsRustLibApi, NtsRustLibApiImpl, NtsRustLibWire> {
  @internal
  static final instance = NtsRustLib._();

  NtsRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    NtsRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required NtsRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<NtsRustLibApiImpl, NtsRustLibWire>
  get apiImplConstructor => NtsRustLibApiImpl.new;

  @override
  WireConstructor<NtsRustLibWire> get wireConstructor =>
      NtsRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 412369031;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nts_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class NtsRustLibApi extends BaseApi {
  void crateApiNtsNtsClientClear({required NtsClient that});

  bool crateApiNtsNtsClientInvalidate({
    required NtsClient that,
    required NtsServerSpec spec,
  });

  NtsClient crateApiNtsNtsClientNew();

  Future<NtsTimeSample> crateApiNtsNtsClientQuery({
    required NtsClient that,
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  });

  TrustMode crateApiNtsNtsClientTrustMode({required NtsClient that});

  Future<NtsWarmCookiesOutcome> crateApiNtsNtsClientWarmCookies({
    required NtsClient that,
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  });

  NtsClient crateApiNtsNtsClientWithTrustMode({required TrustMode trustMode});

  Future<void> crateApiSimpleInitApp();

  NtsDnsPoolStats crateApiNtsNtsDnsPoolStats();

  Future<NtsTimeSample> crateApiNtsNtsQuery({
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  });

  NtsTrustStatus crateApiNtsNtsTrustStatus();

  Future<NtsWarmCookiesOutcome> crateApiNtsNtsWarmCookies({
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  });

  Future<PhaseTimings> crateApiNtsPhaseTimingsDefault();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NtsClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NtsClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NtsClientPtr;
}

class NtsRustLibApiImpl extends NtsRustLibApiImplPlatform
    implements NtsRustLibApi {
  NtsRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiNtsNtsClientClear({required NtsClient that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsClientClearConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientClearConstMeta =>
      const TaskConstMeta(debugName: "NtsClient_clear", argNames: ["that"]);

  @override
  bool crateApiNtsNtsClientInvalidate({
    required NtsClient that,
    required NtsServerSpec spec,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
            that,
            serializer,
          );
          sse_encode_box_autoadd_nts_server_spec(spec, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsClientInvalidateConstMeta,
        argValues: [that, spec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientInvalidateConstMeta =>
      const TaskConstMeta(
        debugName: "NtsClient_invalidate",
        argNames: ["that", "spec"],
      );

  @override
  NtsClient crateApiNtsNtsClientNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsClientNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientNewConstMeta =>
      const TaskConstMeta(debugName: "NtsClient_new", argNames: []);

  @override
  Future<NtsTimeSample> crateApiNtsNtsClientQuery({
    required NtsClient that,
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
            that,
            serializer,
          );
          sse_encode_box_autoadd_nts_server_spec(spec, serializer);
          sse_encode_u_32(timeoutMs, serializer);
          sse_encode_u_32(dnsConcurrencyCap, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nts_time_sample,
          decodeErrorData: sse_decode_nts_error,
        ),
        constMeta: kCrateApiNtsNtsClientQueryConstMeta,
        argValues: [that, spec, timeoutMs, dnsConcurrencyCap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientQueryConstMeta => const TaskConstMeta(
    debugName: "NtsClient_query",
    argNames: ["that", "spec", "timeoutMs", "dnsConcurrencyCap"],
  );

  @override
  TrustMode crateApiNtsNtsClientTrustMode({required NtsClient that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_trust_mode,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsClientTrustModeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientTrustModeConstMeta =>
      const TaskConstMeta(
        debugName: "NtsClient_trust_mode",
        argNames: ["that"],
      );

  @override
  Future<NtsWarmCookiesOutcome> crateApiNtsNtsClientWarmCookies({
    required NtsClient that,
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
            that,
            serializer,
          );
          sse_encode_box_autoadd_nts_server_spec(spec, serializer);
          sse_encode_u_32(timeoutMs, serializer);
          sse_encode_u_32(dnsConcurrencyCap, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nts_warm_cookies_outcome,
          decodeErrorData: sse_decode_nts_error,
        ),
        constMeta: kCrateApiNtsNtsClientWarmCookiesConstMeta,
        argValues: [that, spec, timeoutMs, dnsConcurrencyCap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientWarmCookiesConstMeta =>
      const TaskConstMeta(
        debugName: "NtsClient_warm_cookies",
        argNames: ["that", "spec", "timeoutMs", "dnsConcurrencyCap"],
      );

  @override
  NtsClient crateApiNtsNtsClientWithTrustMode({required TrustMode trustMode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_trust_mode(trustMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsClientWithTrustModeConstMeta,
        argValues: [trustMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsClientWithTrustModeConstMeta =>
      const TaskConstMeta(
        debugName: "NtsClient_with_trust_mode",
        argNames: ["trustMode"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  NtsDnsPoolStats crateApiNtsNtsDnsPoolStats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nts_dns_pool_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsDnsPoolStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsDnsPoolStatsConstMeta =>
      const TaskConstMeta(debugName: "nts_dns_pool_stats", argNames: []);

  @override
  Future<NtsTimeSample> crateApiNtsNtsQuery({
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_nts_server_spec(spec, serializer);
          sse_encode_u_32(timeoutMs, serializer);
          sse_encode_u_32(dnsConcurrencyCap, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nts_time_sample,
          decodeErrorData: sse_decode_nts_error,
        ),
        constMeta: kCrateApiNtsNtsQueryConstMeta,
        argValues: [spec, timeoutMs, dnsConcurrencyCap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsQueryConstMeta => const TaskConstMeta(
    debugName: "nts_query",
    argNames: ["spec", "timeoutMs", "dnsConcurrencyCap"],
  );

  @override
  NtsTrustStatus crateApiNtsNtsTrustStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nts_trust_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsNtsTrustStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsTrustStatusConstMeta =>
      const TaskConstMeta(debugName: "nts_trust_status", argNames: []);

  @override
  Future<NtsWarmCookiesOutcome> crateApiNtsNtsWarmCookies({
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_nts_server_spec(spec, serializer);
          sse_encode_u_32(timeoutMs, serializer);
          sse_encode_u_32(dnsConcurrencyCap, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nts_warm_cookies_outcome,
          decodeErrorData: sse_decode_nts_error,
        ),
        constMeta: kCrateApiNtsNtsWarmCookiesConstMeta,
        argValues: [spec, timeoutMs, dnsConcurrencyCap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsNtsWarmCookiesConstMeta => const TaskConstMeta(
    debugName: "nts_warm_cookies",
    argNames: ["spec", "timeoutMs", "dnsConcurrencyCap"],
  );

  @override
  Future<PhaseTimings> crateApiNtsPhaseTimingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_phase_timings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNtsPhaseTimingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNtsPhaseTimingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "phase_timings_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NtsClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NtsClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient;

  @protected
  NtsClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NtsClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NtsClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NtsClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NtsClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NtsClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NtsServerSpec dco_decode_box_autoadd_nts_server_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_nts_server_spec(raw);
  }

  @protected
  TrustBackend dco_decode_box_autoadd_trust_backend(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_trust_backend(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NtsDnsPoolStats dco_decode_nts_dns_pool_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NtsDnsPoolStats(
      inFlight: dco_decode_u_32(arr[0]),
      highWaterMark: dco_decode_u_32(arr[1]),
      recovered: dco_decode_u_64(arr[2]),
      refused: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  NtsError dco_decode_nts_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NtsError_InvalidSpec(dco_decode_String(raw[1]));
      case 1:
        return NtsError_Network(
          message: dco_decode_String(raw[1]),
          trustBackend: dco_decode_opt_box_autoadd_trust_backend(raw[2]),
        );
      case 2:
        return NtsError_KeProtocol(
          message: dco_decode_String(raw[1]),
          trustBackend: dco_decode_opt_box_autoadd_trust_backend(raw[2]),
        );
      case 3:
        return NtsError_NtpProtocol(
          message: dco_decode_String(raw[1]),
          trustBackend: dco_decode_opt_box_autoadd_trust_backend(raw[2]),
        );
      case 4:
        return NtsError_Authentication(
          message: dco_decode_String(raw[1]),
          trustBackend: dco_decode_opt_box_autoadd_trust_backend(raw[2]),
        );
      case 5:
        return NtsError_Timeout(
          phase: dco_decode_timeout_phase(raw[1]),
          trustBackend: dco_decode_opt_box_autoadd_trust_backend(raw[2]),
        );
      case 6:
        return NtsError_NoCookies(
          trustBackend: dco_decode_opt_box_autoadd_trust_backend(raw[1]),
        );
      case 7:
        return NtsError_TrustBackendUnavailable(dco_decode_String(raw[1]));
      case 8:
        return NtsError_Internal(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NtsServerSpec dco_decode_nts_server_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NtsServerSpec(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
    );
  }

  @protected
  NtsTimeSample dco_decode_nts_time_sample(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NtsTimeSample(
      utcUnixMicros: dco_decode_i_64(arr[0]),
      roundTripMicros: dco_decode_i_64(arr[1]),
      serverStratum: dco_decode_u_8(arr[2]),
      aeadId: dco_decode_u_16(arr[3]),
      freshCookies: dco_decode_u_32(arr[4]),
      phaseTimings: dco_decode_phase_timings(arr[5]),
      trustBackend: dco_decode_trust_backend(arr[6]),
    );
  }

  @protected
  NtsTrustStatus dco_decode_nts_trust_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NtsTrustStatus(
      defaultClientBackend: dco_decode_opt_box_autoadd_trust_backend(arr[0]),
      defaultBackendPlatformCount: dco_decode_u_64(arr[1]),
      defaultBackendHybridCount: dco_decode_u_64(arr[2]),
      defaultBackendWebpkiCount: dco_decode_u_64(arr[3]),
      androidPlatformInitSucceeded: dco_decode_bool(arr[4]),
      androidHybridFallbackCount: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  NtsWarmCookiesOutcome dco_decode_nts_warm_cookies_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NtsWarmCookiesOutcome(
      freshCookies: dco_decode_u_32(arr[0]),
      phaseTimings: dco_decode_phase_timings(arr[1]),
      trustBackend: dco_decode_trust_backend(arr[2]),
    );
  }

  @protected
  TrustBackend? dco_decode_opt_box_autoadd_trust_backend(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_trust_backend(raw);
  }

  @protected
  PhaseTimings dco_decode_phase_timings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PhaseTimings(
      dnsMicros: dco_decode_i_64(arr[0]),
      connectMicros: dco_decode_i_64(arr[1]),
      tlsHandshakeMicros: dco_decode_i_64(arr[2]),
      keRecordIoMicros: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  TimeoutPhase dco_decode_timeout_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimeoutPhase.values[raw as int];
  }

  @protected
  TrustBackend dco_decode_trust_backend(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrustBackend.values[raw as int];
  }

  @protected
  TrustMode dco_decode_trust_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrustMode.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  NtsClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NtsClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NtsClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NtsClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NtsClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NtsClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NtsServerSpec sse_decode_box_autoadd_nts_server_spec(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_nts_server_spec(deserializer));
  }

  @protected
  TrustBackend sse_decode_box_autoadd_trust_backend(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_trust_backend(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NtsDnsPoolStats sse_decode_nts_dns_pool_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_inFlight = sse_decode_u_32(deserializer);
    final var_highWaterMark = sse_decode_u_32(deserializer);
    final var_recovered = sse_decode_u_64(deserializer);
    final var_refused = sse_decode_u_64(deserializer);
    return NtsDnsPoolStats(
      inFlight: var_inFlight,
      highWaterMark: var_highWaterMark,
      recovered: var_recovered,
      refused: var_refused,
    );
  }

  @protected
  NtsError sse_decode_nts_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        final var_field0 = sse_decode_String(deserializer);
        return NtsError_InvalidSpec(var_field0);
      case 1:
        final var_message = sse_decode_String(deserializer);
        final var_trustBackend = sse_decode_opt_box_autoadd_trust_backend(
          deserializer,
        );
        return NtsError_Network(
          message: var_message,
          trustBackend: var_trustBackend,
        );
      case 2:
        final var_message = sse_decode_String(deserializer);
        final var_trustBackend = sse_decode_opt_box_autoadd_trust_backend(
          deserializer,
        );
        return NtsError_KeProtocol(
          message: var_message,
          trustBackend: var_trustBackend,
        );
      case 3:
        final var_message = sse_decode_String(deserializer);
        final var_trustBackend = sse_decode_opt_box_autoadd_trust_backend(
          deserializer,
        );
        return NtsError_NtpProtocol(
          message: var_message,
          trustBackend: var_trustBackend,
        );
      case 4:
        final var_message = sse_decode_String(deserializer);
        final var_trustBackend = sse_decode_opt_box_autoadd_trust_backend(
          deserializer,
        );
        return NtsError_Authentication(
          message: var_message,
          trustBackend: var_trustBackend,
        );
      case 5:
        final var_phase = sse_decode_timeout_phase(deserializer);
        final var_trustBackend = sse_decode_opt_box_autoadd_trust_backend(
          deserializer,
        );
        return NtsError_Timeout(
          phase: var_phase,
          trustBackend: var_trustBackend,
        );
      case 6:
        final var_trustBackend = sse_decode_opt_box_autoadd_trust_backend(
          deserializer,
        );
        return NtsError_NoCookies(trustBackend: var_trustBackend);
      case 7:
        final var_field0 = sse_decode_String(deserializer);
        return NtsError_TrustBackendUnavailable(var_field0);
      case 8:
        final var_field0 = sse_decode_String(deserializer);
        return NtsError_Internal(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NtsServerSpec sse_decode_nts_server_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_host = sse_decode_String(deserializer);
    final var_port = sse_decode_u_16(deserializer);
    return NtsServerSpec(host: var_host, port: var_port);
  }

  @protected
  NtsTimeSample sse_decode_nts_time_sample(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_utcUnixMicros = sse_decode_i_64(deserializer);
    final var_roundTripMicros = sse_decode_i_64(deserializer);
    final var_serverStratum = sse_decode_u_8(deserializer);
    final var_aeadId = sse_decode_u_16(deserializer);
    final var_freshCookies = sse_decode_u_32(deserializer);
    final var_phaseTimings = sse_decode_phase_timings(deserializer);
    final var_trustBackend = sse_decode_trust_backend(deserializer);
    return NtsTimeSample(
      utcUnixMicros: var_utcUnixMicros,
      roundTripMicros: var_roundTripMicros,
      serverStratum: var_serverStratum,
      aeadId: var_aeadId,
      freshCookies: var_freshCookies,
      phaseTimings: var_phaseTimings,
      trustBackend: var_trustBackend,
    );
  }

  @protected
  NtsTrustStatus sse_decode_nts_trust_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_defaultClientBackend = sse_decode_opt_box_autoadd_trust_backend(
      deserializer,
    );
    final var_defaultBackendPlatformCount = sse_decode_u_64(deserializer);
    final var_defaultBackendHybridCount = sse_decode_u_64(deserializer);
    final var_defaultBackendWebpkiCount = sse_decode_u_64(deserializer);
    final var_androidPlatformInitSucceeded = sse_decode_bool(deserializer);
    final var_androidHybridFallbackCount = sse_decode_u_64(deserializer);
    return NtsTrustStatus(
      defaultClientBackend: var_defaultClientBackend,
      defaultBackendPlatformCount: var_defaultBackendPlatformCount,
      defaultBackendHybridCount: var_defaultBackendHybridCount,
      defaultBackendWebpkiCount: var_defaultBackendWebpkiCount,
      androidPlatformInitSucceeded: var_androidPlatformInitSucceeded,
      androidHybridFallbackCount: var_androidHybridFallbackCount,
    );
  }

  @protected
  NtsWarmCookiesOutcome sse_decode_nts_warm_cookies_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_freshCookies = sse_decode_u_32(deserializer);
    final var_phaseTimings = sse_decode_phase_timings(deserializer);
    final var_trustBackend = sse_decode_trust_backend(deserializer);
    return NtsWarmCookiesOutcome(
      freshCookies: var_freshCookies,
      phaseTimings: var_phaseTimings,
      trustBackend: var_trustBackend,
    );
  }

  @protected
  TrustBackend? sse_decode_opt_box_autoadd_trust_backend(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_trust_backend(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PhaseTimings sse_decode_phase_timings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_dnsMicros = sse_decode_i_64(deserializer);
    final var_connectMicros = sse_decode_i_64(deserializer);
    final var_tlsHandshakeMicros = sse_decode_i_64(deserializer);
    final var_keRecordIoMicros = sse_decode_i_64(deserializer);
    return PhaseTimings(
      dnsMicros: var_dnsMicros,
      connectMicros: var_connectMicros,
      tlsHandshakeMicros: var_tlsHandshakeMicros,
      keRecordIoMicros: var_keRecordIoMicros,
    );
  }

  @protected
  TimeoutPhase sse_decode_timeout_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return TimeoutPhase.values[inner];
  }

  @protected
  TrustBackend sse_decode_trust_backend(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return TrustBackend.values[inner];
  }

  @protected
  TrustMode sse_decode_trust_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return TrustMode.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    NtsClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NtsClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    NtsClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NtsClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    NtsClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NtsClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_nts_server_spec(
    NtsServerSpec self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_nts_server_spec(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_trust_backend(
    TrustBackend self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_trust_backend(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_nts_dns_pool_stats(
    NtsDnsPoolStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.inFlight, serializer);
    sse_encode_u_32(self.highWaterMark, serializer);
    sse_encode_u_64(self.recovered, serializer);
    sse_encode_u_64(self.refused, serializer);
  }

  @protected
  void sse_encode_nts_error(NtsError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NtsError_InvalidSpec(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case NtsError_Network(
        message: final message,
        trustBackend: final trustBackend,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(message, serializer);
        sse_encode_opt_box_autoadd_trust_backend(trustBackend, serializer);
      case NtsError_KeProtocol(
        message: final message,
        trustBackend: final trustBackend,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
        sse_encode_opt_box_autoadd_trust_backend(trustBackend, serializer);
      case NtsError_NtpProtocol(
        message: final message,
        trustBackend: final trustBackend,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
        sse_encode_opt_box_autoadd_trust_backend(trustBackend, serializer);
      case NtsError_Authentication(
        message: final message,
        trustBackend: final trustBackend,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
        sse_encode_opt_box_autoadd_trust_backend(trustBackend, serializer);
      case NtsError_Timeout(
        phase: final phase,
        trustBackend: final trustBackend,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_timeout_phase(phase, serializer);
        sse_encode_opt_box_autoadd_trust_backend(trustBackend, serializer);
      case NtsError_NoCookies(trustBackend: final trustBackend):
        sse_encode_i_32(6, serializer);
        sse_encode_opt_box_autoadd_trust_backend(trustBackend, serializer);
      case NtsError_TrustBackendUnavailable(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case NtsError_Internal(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_nts_server_spec(
    NtsServerSpec self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_nts_time_sample(
    NtsTimeSample self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.utcUnixMicros, serializer);
    sse_encode_i_64(self.roundTripMicros, serializer);
    sse_encode_u_8(self.serverStratum, serializer);
    sse_encode_u_16(self.aeadId, serializer);
    sse_encode_u_32(self.freshCookies, serializer);
    sse_encode_phase_timings(self.phaseTimings, serializer);
    sse_encode_trust_backend(self.trustBackend, serializer);
  }

  @protected
  void sse_encode_nts_trust_status(
    NtsTrustStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_trust_backend(
      self.defaultClientBackend,
      serializer,
    );
    sse_encode_u_64(self.defaultBackendPlatformCount, serializer);
    sse_encode_u_64(self.defaultBackendHybridCount, serializer);
    sse_encode_u_64(self.defaultBackendWebpkiCount, serializer);
    sse_encode_bool(self.androidPlatformInitSucceeded, serializer);
    sse_encode_u_64(self.androidHybridFallbackCount, serializer);
  }

  @protected
  void sse_encode_nts_warm_cookies_outcome(
    NtsWarmCookiesOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.freshCookies, serializer);
    sse_encode_phase_timings(self.phaseTimings, serializer);
    sse_encode_trust_backend(self.trustBackend, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_trust_backend(
    TrustBackend? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_trust_backend(self, serializer);
    }
  }

  @protected
  void sse_encode_phase_timings(PhaseTimings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.dnsMicros, serializer);
    sse_encode_i_64(self.connectMicros, serializer);
    sse_encode_i_64(self.tlsHandshakeMicros, serializer);
    sse_encode_i_64(self.keRecordIoMicros, serializer);
  }

  @protected
  void sse_encode_timeout_phase(TimeoutPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_trust_backend(TrustBackend self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_trust_mode(TrustMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class NtsClientImpl extends RustOpaque implements NtsClient {
  // Not to be used by end users
  NtsClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NtsClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        NtsRustLib.instance.api.rust_arc_increment_strong_count_NtsClient,
    rustArcDecrementStrongCount:
        NtsRustLib.instance.api.rust_arc_decrement_strong_count_NtsClient,
    rustArcDecrementStrongCountPtr:
        NtsRustLib.instance.api.rust_arc_decrement_strong_count_NtsClientPtr,
  );

  /// Drop every cached session. Cheap; intended for test cleanup
  /// and for apps that want to bound long-lived process memory by
  /// resetting the cache between work batches.
  ///
  /// Marked `#[flutter_rust_bridge::frb(sync)]` for the same
  /// reason as `invalidate`: one mutex acquisition and one
  /// `HashMap::clear`.
  void clear() => NtsRustLib.instance.api.crateApiNtsNtsClientClear(that: this);

  /// Drop the cached session for `spec`'s `host:port`, if any.
  /// Returns `true` if an entry was removed, `false` if no session
  /// was cached for that key. The next `query` or `warm_cookies`
  /// (`query` / `warmCookies` on the Dart side) for that spec
  /// triggers a fresh NTS-KE handshake.
  ///
  /// Does not validate `spec`. An invalid spec (empty host or zero
  /// port) trivially has no cached session and returns `false`.
  ///
  /// Marked `#[flutter_rust_bridge::frb(sync)]` so cache
  /// invalidation does not pay an isolate-hop round-trip; the
  /// underlying operation is one mutex acquisition and one
  /// `HashMap::remove`.
  bool invalidate({required NtsServerSpec spec}) => NtsRustLib.instance.api
      .crateApiNtsNtsClientInvalidate(that: this, spec: spec);

  /// Per-client equivalent of the top-level `nts_query`
  /// (`ntsQuery` on the Dart side).
  Future<NtsTimeSample> query({
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  }) => NtsRustLib.instance.api.crateApiNtsNtsClientQuery(
    that: this,
    spec: spec,
    timeoutMs: timeoutMs,
    dnsConcurrencyCap: dnsConcurrencyCap,
  );

  /// Trust-anchor policy this client was constructed with. Useful
  /// for diagnostics and for callers that round-trip a client
  /// handle through their own configuration layer and need to
  /// re-derive the policy without keeping a parallel record.
  TrustMode trustMode() =>
      NtsRustLib.instance.api.crateApiNtsNtsClientTrustMode(that: this);

  /// Per-client equivalent of the top-level `nts_warm_cookies`
  /// (`ntsWarmCookies` on the Dart side).
  Future<NtsWarmCookiesOutcome> warmCookies({
    required NtsServerSpec spec,
    required int timeoutMs,
    required int dnsConcurrencyCap,
  }) => NtsRustLib.instance.api.crateApiNtsNtsClientWarmCookies(
    that: this,
    spec: spec,
    timeoutMs: timeoutMs,
    dnsConcurrencyCap: dnsConcurrencyCap,
  );
}
