// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field, public_member_api_docs

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/nts.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class NtsRustLibApiImplPlatform extends BaseApiImpl<NtsRustLibWire> {
  NtsRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NtsClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient;

  @protected
  NtsClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    dynamic raw,
  );

  @protected
  NtsClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    dynamic raw,
  );

  @protected
  NtsClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NtsServerSpec dco_decode_box_autoadd_nts_server_spec(dynamic raw);

  @protected
  TrustBackend dco_decode_box_autoadd_trust_backend(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NtsDnsPoolStats dco_decode_nts_dns_pool_stats(dynamic raw);

  @protected
  NtsError dco_decode_nts_error(dynamic raw);

  @protected
  NtsServerSpec dco_decode_nts_server_spec(dynamic raw);

  @protected
  NtsTimeSample dco_decode_nts_time_sample(dynamic raw);

  @protected
  NtsTrustStatus dco_decode_nts_trust_status(dynamic raw);

  @protected
  NtsWarmCookiesOutcome dco_decode_nts_warm_cookies_outcome(dynamic raw);

  @protected
  TrustBackend? dco_decode_opt_box_autoadd_trust_backend(dynamic raw);

  @protected
  PhaseTimings dco_decode_phase_timings(dynamic raw);

  @protected
  TimeoutPhase dco_decode_timeout_phase(dynamic raw);

  @protected
  TrustBackend dco_decode_trust_backend(dynamic raw);

  @protected
  TrustMode dco_decode_trust_mode(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  NtsClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    SseDeserializer deserializer,
  );

  @protected
  NtsClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    SseDeserializer deserializer,
  );

  @protected
  NtsClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NtsServerSpec sse_decode_box_autoadd_nts_server_spec(
    SseDeserializer deserializer,
  );

  @protected
  TrustBackend sse_decode_box_autoadd_trust_backend(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NtsDnsPoolStats sse_decode_nts_dns_pool_stats(SseDeserializer deserializer);

  @protected
  NtsError sse_decode_nts_error(SseDeserializer deserializer);

  @protected
  NtsServerSpec sse_decode_nts_server_spec(SseDeserializer deserializer);

  @protected
  NtsTimeSample sse_decode_nts_time_sample(SseDeserializer deserializer);

  @protected
  NtsTrustStatus sse_decode_nts_trust_status(SseDeserializer deserializer);

  @protected
  NtsWarmCookiesOutcome sse_decode_nts_warm_cookies_outcome(
    SseDeserializer deserializer,
  );

  @protected
  TrustBackend? sse_decode_opt_box_autoadd_trust_backend(
    SseDeserializer deserializer,
  );

  @protected
  PhaseTimings sse_decode_phase_timings(SseDeserializer deserializer);

  @protected
  TimeoutPhase sse_decode_timeout_phase(SseDeserializer deserializer);

  @protected
  TrustBackend sse_decode_trust_backend(SseDeserializer deserializer);

  @protected
  TrustMode sse_decode_trust_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    NtsClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    NtsClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    NtsClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_nts_server_spec(
    NtsServerSpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trust_backend(
    TrustBackend self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nts_dns_pool_stats(
    NtsDnsPoolStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nts_error(NtsError self, SseSerializer serializer);

  @protected
  void sse_encode_nts_server_spec(NtsServerSpec self, SseSerializer serializer);

  @protected
  void sse_encode_nts_time_sample(NtsTimeSample self, SseSerializer serializer);

  @protected
  void sse_encode_nts_trust_status(
    NtsTrustStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nts_warm_cookies_outcome(
    NtsWarmCookiesOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_trust_backend(
    TrustBackend? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_phase_timings(PhaseTimings self, SseSerializer serializer);

  @protected
  void sse_encode_timeout_phase(TimeoutPhase self, SseSerializer serializer);

  @protected
  void sse_encode_trust_backend(TrustBackend self, SseSerializer serializer);

  @protected
  void sse_encode_trust_mode(TrustMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class NtsRustLibWire implements BaseWire {
  NtsRustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
        ptr,
      );
}

@JS('wasm_bindgen')
external NtsRustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type NtsRustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNtsClient(
    int ptr,
  );
}
