// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import, public_member_api_docs

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'nts.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `arm_recv_against_call_deadline`, `bind_connected_udp_using`, `bind_connected_udp`, `checkout`, `cookies_remaining`, `deposit_cookies`, `effective_dns_concurrency_cap`, `effective_timeout`, `establish_session`, `evict_session`, `new`, `next_session_generation`, `ntp64_to_unix_micros`, `remaining_budget_or_ntp_timeout`, `remaining_or_timeout`, `remaining`, `session_key`, `sessions`, `system_time_to_ntp64`, `unix_duration_to_ntp64`, `validate`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `QueryContext`, `Session`, `UdpBindOutcome`, `UdpDeadline`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

/// Snapshot the bounded DNS resolver pool counters. Reads four atomics
/// with `Relaxed` ordering; the snapshot is intended for
/// human / dashboard consumption, not for synchronisation. See
/// [`NtsDnsPoolStats`] for the diagnostic signatures and
/// `ARCHITECTURE.md`'s "Timeout budget and bounded DNS" section for
/// the operational shape.
///
/// Marked `#[frb(sync)]` so reading four atomics does not pay the
/// future-marshalling overhead a default FRB binding would impose;
/// the function is cheap enough to call from a UI poll loop without
/// thinking about isolate hops.
NtsDnsPoolStats ntsDnsPoolStats() =>
    RustLib.instance.api.crateApiNtsNtsDnsPoolStats();

/// Run a complete authenticated NTPv4 exchange against `spec`.
///
/// On the first call (or after the cookie pool is exhausted) this performs a
/// full NTS-KE handshake before sending the NTPv4 request; subsequent calls
/// reuse the cached AEAD keys and spend a stored cookie. `timeout_ms` is a
/// single global wall-clock budget that spans DNS, NTS-KE (TCP connect, TLS
/// handshake, record I/O) and the AEAD-NTPv4 UDP exchange as one shrinking
/// deadline; pass `0` for the built-in `5000` ms default.
///
/// `dns_concurrency_cap` is a per-call ceiling on the process-wide bounded
/// DNS resolver (see the module docs in `nts::dns`): if the global in-flight
/// counter has already reached this value when the call attempts a lookup,
/// the call short-circuits with `NtsError::Timeout` instead of spawning
/// another worker thread. The cap defaults (when `0` is passed) to a
/// mobile-friendly value chosen to bound the worst-case stack-leak from a
/// blackholed resolver to a few MB. Server-side callers that legitimately
/// need higher fan-out can override it per call. Because the cap compares
/// against a global counter, two concurrent callers with different caps
/// share the same in-flight pool: the effective ceiling at any moment is
/// whichever caller is currently being admitted.
///
/// The returned [`NtsTimeSample`] exposes the raw protocol primitives, not a
/// finished synchronized clock. `utc_unix_micros` is the server transmit
/// timestamp exactly as it appeared on the wire; it does not include any
/// compensation for the one-way network delay between the server and this
/// caller. To approximate the server's clock at the moment the reply
/// arrived, callers should add `round_trip_micros / 2` to `utc_unix_micros`
/// (the standard NTP assumption of a symmetric path). For high-precision
/// synchronization, take a burst of samples and pick the one with the
/// smallest `round_trip_micros` before applying that adjustment.
Future<NtsTimeSample> ntsQuery({
  required NtsServerSpec spec,
  required int timeoutMs,
  required int dnsConcurrencyCap,
}) => RustLib.instance.api.crateApiNtsNtsQuery(
  spec: spec,
  timeoutMs: timeoutMs,
  dnsConcurrencyCap: dnsConcurrencyCap,
);

/// Force a fresh NTS-KE handshake against `spec` and return the
/// cookie count along with the per-phase wall-clock breakdown.
/// Replaces any cached session for that spec.
///
/// `timeout_ms` and `dns_concurrency_cap` carry the same semantics as on
/// [`nts_query`]; pass `0` for either to inherit the built-in default.
///
/// The returned [`NtsWarmCookiesOutcome::phase_timings`] only covers
/// the KE handshake (DNS, connect, TLS, KE record I/O) — there is no
/// UDP NTP exchange on this path, so the `Ntp` phase is implicitly
/// zero and not represented.
Future<NtsWarmCookiesOutcome> ntsWarmCookies({
  required NtsServerSpec spec,
  required int timeoutMs,
  required int dnsConcurrencyCap,
}) => RustLib.instance.api.crateApiNtsNtsWarmCookies(
  spec: spec,
  timeoutMs: timeoutMs,
  dnsConcurrencyCap: dnsConcurrencyCap,
);

/// Snapshot of the bounded DNS resolver pool counters.
///
/// All counters are process-wide and include workers spawned by every
/// concurrent caller, including those that passed a different
/// `dns_concurrency_cap` (the underlying pool is shared by design — see
/// the `nts::dns` module docs for the global-counter rationale). The
/// snapshot is racy by construction: each counter is read with an
/// independent atomic `Relaxed` load, so combinations across counters
/// can be slightly stale — e.g. `in_flight` lagging `recovered` by one
/// bump, or `in_flight > high_water_mark` for the few-nanosecond
/// window between a worker's admission `fetch_add` on `in_flight` and
/// the subsequent `fetch_max` on `high_water_mark` in
/// `try_acquire_slot`. The actual guarantee is per-counter
/// monotonicity in each counter's natural direction (cumulative
/// counters and `high_water_mark` never decrease across consecutive
/// snapshots; every loaded value is one the counter actually held at
/// some real moment), not a cross-counter invariant within a single
/// snapshot. The snapshot does not reset cumulative counters; callers
/// that want windowed measurements snapshot at `t0` and `t1` and
/// subtract.
///
/// Operators can use the four counters to distinguish three failure
/// modes that all collapse onto `NtsError::Timeout` in the hot-path
/// error contract:
///
/// - **Healthy resolver, occasional bursts** — `in_flight` oscillates
///   below the cap, `high_water_mark` plateaus a few steps above
///   steady state, `recovered` climbs in lockstep with traffic,
///   `refused` stays flat.
/// - **Cap-bound deployment** — `refused` is climbing; raising the
///   `dns_concurrency_cap` argument on `nts_query` /
///   `nts_warm_cookies` would lower the timeout error rate.
/// - **libc-level resolver wedge** — `in_flight` is pinned at the
///   cap, `recovered` is flat, `refused` is climbing. The system
///   resolver is not making progress; raising the cap would only push
///   more threads into the same wedge.
class NtsDnsPoolStats {
  /// Live count of resolver workers currently pinned in the system
  /// resolver. The next admission decision will compare its `cap`
  /// argument against this number.
  final int inFlight;

  /// Largest value `in_flight` has reached since process start, as
  /// published by the `fetch_max` in `try_acquire_slot` after each
  /// successful admission. Non-decreasing across consecutive
  /// snapshots, but **not** a cross-counter invariant within a
  /// single snapshot: see the struct-level note on the transient
  /// window where `in_flight > high_water_mark` between a worker's
  /// admission increment and the subsequent `fetch_max`.
  final int highWaterMark;

  /// Cumulative count of detached workers that have completed and
  /// released their slot since process start. `u64` because the
  /// counter grows monotonically over a process lifetime and a
  /// 32-bit wraparound would be visible on long-running CLI / server
  /// builds with a saturated resolver.
  final BigInt recovered;

  /// Cumulative count of admission attempts that were refused
  /// because the cap was reached since process start. The expected
  /// delta when the resolver is healthy is zero.
  final BigInt refused;

  const NtsDnsPoolStats({
    required this.inFlight,
    required this.highWaterMark,
    required this.recovered,
    required this.refused,
  });

  @override
  int get hashCode =>
      inFlight.hashCode ^
      highWaterMark.hashCode ^
      recovered.hashCode ^
      refused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsDnsPoolStats &&
          runtimeType == other.runtimeType &&
          inFlight == other.inFlight &&
          highWaterMark == other.highWaterMark &&
          recovered == other.recovered &&
          refused == other.refused;
}

@freezed
sealed class NtsError with _$NtsError implements FrbException {
  const NtsError._();

  /// `spec` was rejected before any I/O happened.
  const factory NtsError.invalidSpec(String field0) = NtsError_InvalidSpec;

  /// TCP/UDP I/O error or connection failure.
  const factory NtsError.network(String field0) = NtsError_Network;

  /// TLS handshake or NTS-KE record exchange failed.
  const factory NtsError.keProtocol(String field0) = NtsError_KeProtocol;

  /// NTPv4 packet parsing or extension validation failed.
  const factory NtsError.ntpProtocol(String field0) = NtsError_NtpProtocol;

  /// AEAD seal/open failed (tag mismatch, malformed input).
  const factory NtsError.authentication(String field0) =
      NtsError_Authentication;

  /// Wall-clock budget elapsed inside one of the call's pre-NTP or
  /// NTP phases. The [`TimeoutPhase`] payload identifies which
  /// phase tripped the deadline so callers can choose the right
  /// remediation (raise the resolver cap on `DnsSaturation`,
  /// lengthen `timeout_ms` on `DnsTimeout` / `Connect` / `Tls` /
  /// `KeRecordIo` / `Ntp`, etc.). See [`TimeoutPhase`] for the full
  /// taxonomy.
  const factory NtsError.timeout(TimeoutPhase field0) = NtsError_Timeout;

  /// Cookie jar empty after a handshake (server delivered none).
  const factory NtsError.noCookies() = NtsError_NoCookies;

  /// Bug guard for unreachable internal states.
  const factory NtsError.internal(String field0) = NtsError_Internal;
}

/// Address of an NTS-KE endpoint.
class NtsServerSpec {
  /// Hostname for TLS SNI and certificate validation.
  final String host;

  /// TCP port; pass `4460` (the IANA-assigned NTS-KE default, RFC 8915 §6)
  /// unless the deployment overrides it.
  final int port;

  const NtsServerSpec({required this.host, required this.port});

  @override
  int get hashCode => host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsServerSpec &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port;
}

/// Successful authenticated NTPv4 sample.
///
/// This is the raw output of one protocol exchange, not a synchronized
/// clock. See [`nts_query`] for the recommended burst-and-RTT-compensation
/// pattern callers should layer on top.
class NtsTimeSample {
  /// Server transmit time as microseconds since the Unix epoch, taken
  /// directly from the NTPv4 reply. No correction for the one-way
  /// network delay between the server and this caller is applied; add
  /// `round_trip_micros / 2` to estimate the server's clock at the
  /// moment the reply arrived.
  final PlatformInt64 utcUnixMicros;

  /// Wall-clock microseconds elapsed between the AEAD-NTPv4 UDP
  /// `send` and the matching `recv`. This *is* the UDP-phase
  /// wall-clock cost — there is no separate `udp_send_recv_micros`
  /// in [`PhaseTimings`] because that would publish the same fact
  /// in two fields.
  final PlatformInt64 roundTripMicros;

  /// NTP stratum reported by the server (RFC 5905 §7.3).
  final int serverStratum;

  /// AEAD algorithm IANA ID negotiated during NTS-KE.
  final int aeadId;

  /// Number of fresh cookies recovered from the encrypted reply.
  final int freshCookies;

  /// Microsecond-resolution wall-clock breakdown of the pre-NTP
  /// phases of this call. Combined with `round_trip_micros`
  /// (Dart: `roundTripMicros`) it accounts for the entire
  /// wall-clock cost of `nts_query` (Dart: `ntsQuery`).
  final PhaseTimings phaseTimings;

  const NtsTimeSample({
    required this.utcUnixMicros,
    required this.roundTripMicros,
    required this.serverStratum,
    required this.aeadId,
    required this.freshCookies,
    required this.phaseTimings,
  });

  @override
  int get hashCode =>
      utcUnixMicros.hashCode ^
      roundTripMicros.hashCode ^
      serverStratum.hashCode ^
      aeadId.hashCode ^
      freshCookies.hashCode ^
      phaseTimings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsTimeSample &&
          runtimeType == other.runtimeType &&
          utcUnixMicros == other.utcUnixMicros &&
          roundTripMicros == other.roundTripMicros &&
          serverStratum == other.serverStratum &&
          aeadId == other.aeadId &&
          freshCookies == other.freshCookies &&
          phaseTimings == other.phaseTimings;
}

/// Successful outcome of [`nts_warm_cookies`].
///
/// Replaces the prior bare `u32` return so the same phase-attribution
/// view available on [`NtsTimeSample`] is also available for the
/// handshake-only path callers use to refill an empty cookie pool.
class NtsWarmCookiesOutcome {
  /// Number of fresh cookies the server delivered with the KE response.
  final int freshCookies;

  /// Microsecond-resolution wall-clock breakdown of the handshake
  /// that produced the cookies. The UDP NTP exchange is not part
  /// of this call, so `dns_micros` (Dart: `dnsMicros`) reflects
  /// only the KE-host lookup.
  final PhaseTimings phaseTimings;

  const NtsWarmCookiesOutcome({
    required this.freshCookies,
    required this.phaseTimings,
  });

  @override
  int get hashCode => freshCookies.hashCode ^ phaseTimings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsWarmCookiesOutcome &&
          runtimeType == other.runtimeType &&
          freshCookies == other.freshCookies &&
          phaseTimings == other.phaseTimings;
}

/// Microsecond-resolution wall-clock breakdown of a successful
/// [`nts_query`] or [`nts_warm_cookies`] call, surfaced on
/// [`NtsTimeSample::phase_timings`] / [`NtsWarmCookiesOutcome::phase_timings`].
///
/// Field semantics match [`KePhaseTimings`] for the four KE-pipeline
/// phases. The UDP send/recv phase has no field of its own; the
/// existing [`NtsTimeSample::round_trip_micros`] already covers it
/// (kept for backward-compatibility on the Dart side and to avoid
/// publishing the same fact in two fields). Callers who want a
/// "preNtp" wall-clock view can sum
/// `dns_micros + connect_micros + tls_handshake_micros +
/// ke_record_io_micros`; the per-call total wall-clock is that sum
/// plus `round_trip_micros`.
///
/// Phases that did not run are reported as `0` rather than absent —
/// e.g. on a cache-hit query (no KE handshake), `connect_micros`,
/// `tls_handshake_micros`, and `ke_record_io_micros` are all `0` and
/// `dns_micros` reflects only the UDP-path lookup of the NTPv4 host.
/// On a fresh-session query both KE-path and UDP-path DNS lookups
/// run; their costs are summed into a single `dns_micros` value so
/// callers do not have to reason about which path contributed.
class PhaseTimings {
  /// Sum of wall-clock microseconds spent in the bounded DNS
  /// resolver across both the KE-host lookup (when a handshake
  /// runs) and the NTPv4-host lookup. Combined into a single
  /// field because callers diagnosing slow DNS care about the
  /// host-level cost regardless of which leg consumed it. See
  /// `ARCHITECTURE.md`'s "Timeout budget and bounded DNS"
  /// section for the resolver semantics.
  final PlatformInt64 dnsMicros;

  /// Wall-clock microseconds spent in the per-address
  /// `TcpStream::connect_timeout` loop during the KE handshake.
  /// `0` on cache-hit queries.
  final PlatformInt64 connectMicros;

  /// Wall-clock microseconds spent on the rustls
  /// `Stream::write_all` + `flush` window during the KE handshake.
  /// In TLS 1.3 this includes the ClientHello/ServerHello/Finished
  /// round-trip plus the initial NTS-KE request write. `0` on
  /// cache-hit queries.
  final PlatformInt64 tlsHandshakeMicros;

  /// Wall-clock microseconds spent in the chunked record-read loop
  /// reading the server's NTS-KE response. `0` on cache-hit queries.
  final PlatformInt64 keRecordIoMicros;

  const PhaseTimings({
    required this.dnsMicros,
    required this.connectMicros,
    required this.tlsHandshakeMicros,
    required this.keRecordIoMicros,
  });

  static Future<PhaseTimings> default_() =>
      RustLib.instance.api.crateApiNtsPhaseTimingsDefault();

  @override
  int get hashCode =>
      dnsMicros.hashCode ^
      connectMicros.hashCode ^
      tlsHandshakeMicros.hashCode ^
      keRecordIoMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhaseTimings &&
          runtimeType == other.runtimeType &&
          dnsMicros == other.dnsMicros &&
          connectMicros == other.connectMicros &&
          tlsHandshakeMicros == other.tlsHandshakeMicros &&
          keRecordIoMicros == other.keRecordIoMicros;
}

/// Phase of an [`nts_query`] / [`nts_warm_cookies`] call whose
/// wall-clock budget elapsed.
///
/// Carried as the payload of [`NtsError::Timeout`] so callers can
/// attribute a failure to a specific pre-NTP step instead of inspecting
/// free-form diagnostic strings. The Rust-side [`KeTimeoutPhase`] for
/// the KE pipeline maps onto this enum via `From`; the `Ntp` variant is
/// added at this layer for the UDP send/recv phase, and the two `Dns*`
/// variants distinguish saturation (cap full) from timeout (resolver
/// slow). See `ARCHITECTURE.md`'s "Phase attribution and timings"
/// section for the full diagnostic shape.
enum TimeoutPhase {
  /// Bounded DNS resolver pool was already at capacity when the call
  /// arrived, so admission was refused without spawning a worker.
  /// Distinct from [`Self::DnsTimeout`]: raising
  /// `dns_concurrency_cap` or waiting for the in-flight pool to
  /// drain is the appropriate remediation, not lengthening
  /// `timeout_ms`.
  dnsSaturation,

  /// System resolver took longer than the remaining budget.
  /// Lengthening `timeout_ms` *or* swapping in a faster recursive
  /// resolver are the appropriate remediations; raising the
  /// concurrency cap would only allow more threads to wedge in the
  /// same lookup.
  dnsTimeout,

  /// Per-address `TcpStream::connect_timeout` budget elapsed before
  /// any KE-host candidate accepted, or the global deadline expired
  /// before the connect loop could try the next address.
  connect,

  /// TLS handshake / initial NTS-KE request write tripped the
  /// deadline. In TLS 1.3 the first write is what completes the
  /// ClientHello/ServerHello/Finished round-trip.
  tls,

  /// Read of the NTS-KE response records exceeded the remaining
  /// budget — the server completed TLS but is now drip-feeding (or
  /// has stalled completely on) the record exchange.
  keRecordIo,

  /// AEAD-NTPv4 UDP `send` / `recv` exceeded the remaining budget.
  /// Either the destination is unreachable or the wire round-trip
  /// time was too long for the configured budget.
  ntp,
}
