// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import, public_member_api_docs

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'nts.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bind_connected_udp_using`, `bind_connected_udp`, `checkout`, `cookies_remaining`, `deposit_cookies`, `effective_dns_concurrency_cap`, `effective_timeout`, `establish_session`, `new`, `next_session_generation`, `ntp64_to_unix_micros`, `remaining_or_timeout`, `remaining`, `session_key`, `sessions`, `system_time_to_ntp64`, `unix_duration_to_ntp64`, `validate`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `QueryContext`, `Session`, `UdpDeadline`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Snapshot the bounded DNS resolver pool counters. Reads four atomics
/// with `Relaxed` ordering; the snapshot is intended for
/// human / dashboard consumption, not for synchronisation. See
/// [`NtsDnsPoolStats`] for the diagnostic signatures and
/// `ARCHITECTURE.md`'s "Timeout budget and bounded DNS" section for
/// the operational shape.
///
/// Marked `#[frb(sync)]` so reading four atomics does not pay the
/// future-marshalling overhead a default FRB binding would impose;
/// the function is cheap enough to call from a UI poll loop without
/// thinking about isolate hops.
NtsDnsPoolStats ntsDnsPoolStats() =>
    RustLib.instance.api.crateApiNtsNtsDnsPoolStats();

/// Run a complete authenticated NTPv4 exchange against `spec`.
///
/// On the first call (or after the cookie pool is exhausted) this performs a
/// full NTS-KE handshake before sending the NTPv4 request; subsequent calls
/// reuse the cached AEAD keys and spend a stored cookie. `timeout_ms` is a
/// single global wall-clock budget that spans DNS, NTS-KE (TCP connect, TLS
/// handshake, record I/O) and the AEAD-NTPv4 UDP exchange as one shrinking
/// deadline; pass `0` for the built-in `5000` ms default.
///
/// `dns_concurrency_cap` is a per-call ceiling on the process-wide bounded
/// DNS resolver (see the module docs in `nts::dns`): if the global in-flight
/// counter has already reached this value when the call attempts a lookup,
/// the call short-circuits with `NtsError::Timeout` instead of spawning
/// another worker thread. The cap defaults (when `0` is passed) to a
/// mobile-friendly value chosen to bound the worst-case stack-leak from a
/// blackholed resolver to a few MB. Server-side callers that legitimately
/// need higher fan-out can override it per call. Because the cap compares
/// against a global counter, two concurrent callers with different caps
/// share the same in-flight pool: the effective ceiling at any moment is
/// whichever caller is currently being admitted.
///
/// The returned [`NtsTimeSample`] exposes the raw protocol primitives, not a
/// finished synchronized clock. `utc_unix_micros` is the server transmit
/// timestamp exactly as it appeared on the wire; it does not include any
/// compensation for the one-way network delay between the server and this
/// caller. To approximate the server's clock at the moment the reply
/// arrived, callers should add `round_trip_micros / 2` to `utc_unix_micros`
/// (the standard NTP assumption of a symmetric path). For high-precision
/// synchronization, take a burst of samples and pick the one with the
/// smallest `round_trip_micros` before applying that adjustment.
Future<NtsTimeSample> ntsQuery({
  required NtsServerSpec spec,
  required int timeoutMs,
  required int dnsConcurrencyCap,
}) => RustLib.instance.api.crateApiNtsNtsQuery(
  spec: spec,
  timeoutMs: timeoutMs,
  dnsConcurrencyCap: dnsConcurrencyCap,
);

/// Force a fresh NTS-KE handshake against `spec` and return the number of
/// cookies the server delivered. Replaces any cached session for that spec.
///
/// `timeout_ms` and `dns_concurrency_cap` carry the same semantics as on
/// [`nts_query`]; pass `0` for either to inherit the built-in default.
Future<int> ntsWarmCookies({
  required NtsServerSpec spec,
  required int timeoutMs,
  required int dnsConcurrencyCap,
}) => RustLib.instance.api.crateApiNtsNtsWarmCookies(
  spec: spec,
  timeoutMs: timeoutMs,
  dnsConcurrencyCap: dnsConcurrencyCap,
);

/// Snapshot of the bounded DNS resolver pool counters.
///
/// All counters are process-wide and include workers spawned by every
/// concurrent caller, including those that passed a different
/// `dns_concurrency_cap` (the underlying pool is shared by design — see
/// the `nts::dns` module docs for the global-counter rationale). The
/// snapshot is racy by construction: each counter is read with an
/// independent atomic `Relaxed` load, so combinations across counters
/// can be slightly stale — e.g. `in_flight` lagging `recovered` by one
/// bump, or `in_flight > high_water_mark` for the few-nanosecond
/// window between a worker's admission `fetch_add` on `in_flight` and
/// the subsequent `fetch_max` on `high_water_mark` in
/// `try_acquire_slot`. The actual guarantee is per-counter
/// monotonicity in each counter's natural direction (cumulative
/// counters and `high_water_mark` never decrease across consecutive
/// snapshots; every loaded value is one the counter actually held at
/// some real moment), not a cross-counter invariant within a single
/// snapshot. The snapshot does not reset cumulative counters; callers
/// that want windowed measurements snapshot at `t0` and `t1` and
/// subtract.
///
/// Operators can use the four counters to distinguish three failure
/// modes that all collapse onto `NtsError::Timeout` in the hot-path
/// error contract:
///
/// - **Healthy resolver, occasional bursts** — `in_flight` oscillates
///   below the cap, `high_water_mark` plateaus a few steps above
///   steady state, `recovered` climbs in lockstep with traffic,
///   `refused` stays flat.
/// - **Cap-bound deployment** — `refused` is climbing; raising the
///   `dns_concurrency_cap` argument on `nts_query` /
///   `nts_warm_cookies` would lower the timeout error rate.
/// - **libc-level resolver wedge** — `in_flight` is pinned at the
///   cap, `recovered` is flat, `refused` is climbing. The system
///   resolver is not making progress; raising the cap would only push
///   more threads into the same wedge.
class NtsDnsPoolStats {
  /// Live count of resolver workers currently pinned in the system
  /// resolver. The next admission decision will compare its `cap`
  /// argument against this number.
  final int inFlight;

  /// Largest value `in_flight` has reached since process start, as
  /// published by the `fetch_max` in `try_acquire_slot` after each
  /// successful admission. Non-decreasing across consecutive
  /// snapshots, but **not** a cross-counter invariant within a
  /// single snapshot: see the struct-level note on the transient
  /// window where `in_flight > high_water_mark` between a worker's
  /// admission increment and the subsequent `fetch_max`.
  final int highWaterMark;

  /// Cumulative count of detached workers that have completed and
  /// released their slot since process start. `u64` because the
  /// counter grows monotonically over a process lifetime and a
  /// 32-bit wraparound would be visible on long-running CLI / server
  /// builds with a saturated resolver.
  final BigInt recovered;

  /// Cumulative count of admission attempts that were refused
  /// because the cap was reached since process start. The expected
  /// delta when the resolver is healthy is zero.
  final BigInt refused;

  const NtsDnsPoolStats({
    required this.inFlight,
    required this.highWaterMark,
    required this.recovered,
    required this.refused,
  });

  @override
  int get hashCode =>
      inFlight.hashCode ^
      highWaterMark.hashCode ^
      recovered.hashCode ^
      refused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsDnsPoolStats &&
          runtimeType == other.runtimeType &&
          inFlight == other.inFlight &&
          highWaterMark == other.highWaterMark &&
          recovered == other.recovered &&
          refused == other.refused;
}

@freezed
sealed class NtsError with _$NtsError implements FrbException {
  const NtsError._();

  /// `spec` was rejected before any I/O happened.
  const factory NtsError.invalidSpec(String field0) = NtsError_InvalidSpec;

  /// TCP/UDP I/O error or connection failure.
  const factory NtsError.network(String field0) = NtsError_Network;

  /// TLS handshake or NTS-KE record exchange failed.
  const factory NtsError.keProtocol(String field0) = NtsError_KeProtocol;

  /// NTPv4 packet parsing or extension validation failed.
  const factory NtsError.ntpProtocol(String field0) = NtsError_NtpProtocol;

  /// AEAD seal/open failed (tag mismatch, malformed input).
  const factory NtsError.authentication(String field0) =
      NtsError_Authentication;

  /// UDP receive timed out.
  const factory NtsError.timeout() = NtsError_Timeout;

  /// Cookie jar empty after a handshake (server delivered none).
  const factory NtsError.noCookies() = NtsError_NoCookies;

  /// Bug guard for unreachable internal states.
  const factory NtsError.internal(String field0) = NtsError_Internal;
}

/// Address of an NTS-KE endpoint.
class NtsServerSpec {
  /// Hostname for TLS SNI and certificate validation.
  final String host;

  /// TCP port; pass `4460` (the IANA-assigned NTS-KE default, RFC 8915 §6)
  /// unless the deployment overrides it.
  final int port;

  const NtsServerSpec({required this.host, required this.port});

  @override
  int get hashCode => host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsServerSpec &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port;
}

/// Successful authenticated NTPv4 sample.
///
/// This is the raw output of one protocol exchange, not a synchronized
/// clock. See [`nts_query`] for the recommended burst-and-RTT-compensation
/// pattern callers should layer on top.
class NtsTimeSample {
  /// Server transmit time as microseconds since the Unix epoch, taken
  /// directly from the NTPv4 reply. No correction for the one-way
  /// network delay between the server and this caller is applied; add
  /// `round_trip_micros / 2` to estimate the server's clock at the
  /// moment the reply arrived.
  final PlatformInt64 utcUnixMicros;

  /// Wall-clock microseconds elapsed between client send and client receive.
  final PlatformInt64 roundTripMicros;

  /// NTP stratum reported by the server (RFC 5905 §7.3).
  final int serverStratum;

  /// AEAD algorithm IANA ID negotiated during NTS-KE.
  final int aeadId;

  /// Number of fresh cookies recovered from the encrypted reply.
  final int freshCookies;

  const NtsTimeSample({
    required this.utcUnixMicros,
    required this.roundTripMicros,
    required this.serverStratum,
    required this.aeadId,
    required this.freshCookies,
  });

  @override
  int get hashCode =>
      utcUnixMicros.hashCode ^
      roundTripMicros.hashCode ^
      serverStratum.hashCode ^
      aeadId.hashCode ^
      freshCookies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsTimeSample &&
          runtimeType == other.runtimeType &&
          utcUnixMicros == other.utcUnixMicros &&
          roundTripMicros == other.roundTripMicros &&
          serverStratum == other.serverStratum &&
          aeadId == other.aeadId &&
          freshCookies == other.freshCookies;
}
