// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'nts.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bind_connected_udp`, `checkout`, `cookies_remaining`, `deposit_cookies`, `effective_timeout`, `establish_session`, `ntp64_to_unix_micros`, `session_key`, `sessions`, `system_time_to_ntp64`, `unix_duration_to_ntp64`, `validate`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `QueryContext`, `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Run a complete authenticated NTPv4 exchange against `spec`.
///
/// On the first call (or after the cookie pool is exhausted) this performs a
/// full NTS-KE handshake before sending the NTPv4 request; subsequent calls
/// reuse the cached AEAD keys and spend a stored cookie. `timeout_ms` is
/// applied independently to the KE handshake and to the UDP recv; pass 0 for
/// the [`DEFAULT_TIMEOUT_MS`] default.
Future<NtsTimeSample> ntsQuery({
  required NtsServerSpec spec,
  required int timeoutMs,
}) =>
    RustLib.instance.api.crateApiNtsNtsQuery(spec: spec, timeoutMs: timeoutMs);

/// Force a fresh NTS-KE handshake against `spec` and return the number of
/// cookies the server delivered. Replaces any cached session for that spec.
Future<int> ntsWarmCookies({
  required NtsServerSpec spec,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiNtsNtsWarmCookies(
  spec: spec,
  timeoutMs: timeoutMs,
);

@freezed
sealed class NtsError with _$NtsError implements FrbException {
  const NtsError._();

  /// `spec` was rejected before any I/O happened.
  const factory NtsError.invalidSpec(String field0) = NtsError_InvalidSpec;

  /// TCP/UDP I/O error or connection failure.
  const factory NtsError.network(String field0) = NtsError_Network;

  /// TLS handshake or NTS-KE record exchange failed.
  const factory NtsError.keProtocol(String field0) = NtsError_KeProtocol;

  /// NTPv4 packet parsing or extension validation failed.
  const factory NtsError.ntpProtocol(String field0) = NtsError_NtpProtocol;

  /// AEAD seal/open failed (tag mismatch, malformed input).
  const factory NtsError.authentication(String field0) =
      NtsError_Authentication;

  /// UDP receive timed out.
  const factory NtsError.timeout() = NtsError_Timeout;

  /// Cookie jar empty after a handshake (server delivered none).
  const factory NtsError.noCookies() = NtsError_NoCookies;

  /// Bug guard for unreachable internal states.
  const factory NtsError.internal(String field0) = NtsError_Internal;
}

/// Address of an NTS-KE endpoint.
class NtsServerSpec {
  /// Hostname for TLS SNI and certificate validation.
  final String host;

  /// TCP port; pass [`DEFAULT_KE_PORT`] (4460) unless the deployment overrides it.
  final int port;

  const NtsServerSpec({required this.host, required this.port});

  @override
  int get hashCode => host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsServerSpec &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port;
}

/// Successful authenticated NTPv4 sample.
class NtsTimeSample {
  /// Server transmit time as microseconds since the Unix epoch.
  final PlatformInt64 utcUnixMicros;

  /// Wall-clock microseconds elapsed between client send and client receive.
  final PlatformInt64 roundTripMicros;

  /// NTP stratum reported by the server (RFC 5905 §7.3).
  final int serverStratum;

  /// AEAD algorithm IANA ID negotiated during NTS-KE.
  final int aeadId;

  /// Number of fresh cookies recovered from the encrypted reply.
  final int freshCookies;

  const NtsTimeSample({
    required this.utcUnixMicros,
    required this.roundTripMicros,
    required this.serverStratum,
    required this.aeadId,
    required this.freshCookies,
  });

  @override
  int get hashCode =>
      utcUnixMicros.hashCode ^
      roundTripMicros.hashCode ^
      serverStratum.hashCode ^
      aeadId.hashCode ^
      freshCookies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NtsTimeSample &&
          runtimeType == other.runtimeType &&
          utcUnixMicros == other.utcUnixMicros &&
          roundTripMicros == other.roundTripMicros &&
          serverStratum == other.serverStratum &&
          aeadId == other.aeadId &&
          freshCookies == other.freshCookies;
}
