// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns a greeting that round-trips a string across the FFI boundary.
///
/// Used by `test/ffi_smoke_test.dart` to verify codegen, native asset
/// bundling, and the Rust ↔ Dart marshalling layer are all wired up.
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);
